
name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment-name:
        description: 'Choose environment'
        required: true
        type: choice
        options: [java, python]

jobs:
  build-java:
    if: ${{ github.event.inputs.environment-name == 'java' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout UBS_JAVA repo
        uses: actions/checkout@v3
        with:
          repository: sumersovitkargit/UBS_JAVA
          ref: main
          path: java-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build Java Docker image
        run: |
          cd java-repo
          docker build -t java-image:${{ github.sha }} .
          docker tag java-image:${{ github.sha }} java-image:latest

  build-python:
    if: ${{ github.event.inputs.environment-name == 'python' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout UBS_PYTHON repo
        uses: actions/checkout@v3
        with:
          repository: sumersovitkargit/UBS_PYTHON
          ref: main
          path: python-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build Python Docker image
        run: |
          cd python-repo
          docker build -t python-image:${{ github.sha }} .
          docker tag python-image:${{ github.sha }} python-image:latest
