name: Shared Build

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string
      stage:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling repo
        uses: actions/checkout@v3

      - name: Display environment details
        run: |
          echo "Building for environment: ${{ inputs.environment-name }}"
          echo "Deployment stage: ${{ inputs.stage }}"

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.environment-name }}-${{ inputs.stage }}:${{ github.sha }} .
          docker tag ${{ inputs.environment-name }}-${{ inputs.stage }}:${{ github.sha }} ${{ inputs.environment-name }}-${{ inputs.stage }}:latest
